### ISSUE TITLE
What is the state of this repository?

### ISSUE THREAD

**Issue by ypicard** [dsanel/mongoose-delete#102]
Hi,
What is the current situation for this project? Is it abandoned?
The typescript types seem clunky, some issues have been opened for quite a while now, and lack of promise support is sort of suspicious nowadays.

Just want to make sure before I use it in my project, the functionalities would really be useful!

Thanks :)

**Comment by Rush** [comment]
Indeed looks like types are all messed up now.

**Comment by Rush** [comment]
I published .. yet another fork xD https://github.com/Rush/mongoose-delete-plugin

https://www.npmjs.com/package/mongoose-delete-plugin

Changes:
- Made compatible with latest mongoose
- rename all `.delete` methods to `.softDelete`
- bundled typings from `@types/mongoose-delete`

If @dsanel replies I am happy to open a merge request

**Comment by dsanel** [comment]
A new version will be soon, probably next week. After this, I will try to add TypeScript support in the repository too.
