### ISSUE TITLE
Update a soft-deleted document by instance

### ISSUE THREAD

**Issue by et3858** [dsanel/mongoose-delete#106]
Hi.

I have been using this plugin for a while, and one of the things i tested is if I have an instance of a model with a soft-deleted document. When I tested it the instance updated the soft-deleted document for some fields using the `save()` method after using the `delete()` method on the same instance. Here is the code:

```
const mongoose = require("mongoose");
const mongooseDelete = require("mongoose-delete");
const Schema = mongoose.Schema;

const UserSchema = new Schema({
    name: String,
    email: String
});

UserSchema.plugin(mongooseDelete, { overrideMethods: "all" });

const User = mongoose.model("User", UserSchema);


(async function() {
    const user = new User({ name: "John Old", email: "old@john.com" });

    await user.save();
    await user.delete(); // { name: "John Old", email: "old@john.com", deleted: true }

    user.name = "John New";
    user.email = "new@john.com";
    await user.save(); // { name: "John New", email: "new@john.com", deleted: true }
})();
```

**Comment by dsanel** [comment]
Hello @et3858, is this problem for you or do you think it should work differently? I will close this issue now, but if you think it is a problem or if you have PR for this, please be free to create it.
