### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by ajmas** [dsanel/mongoose-delete#108]
Given that a few tickets aren't including any details about the breakage in question, it may be a good idea to provide a default issue template, or maybe even two, one being for bugs and the other for feature requests.

Documentation around this is here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

For the sections, thinking as follows:

  - Bug
    - What broke?
    - What is the expected behaviour?
    - Is there a workaround?
    - Version
      - NodeJS version
      - database version
      - mongo version
      - mongoose version
      - mongoose-delete version
      - Typescript version (if applicable)
  - Feature Request
    - Describe the suggested feature or improvement
    - Can this be achieved now with a workaround?

If this is something you could be interested in, are there any changes to the proposed sections above you'd want?

**Comment by dsanel** [comment]
This is a really interesting and useful proposal. I will ty to add this in the next period. Thx @ajmas
