### ISSUE TITLE
Bulk restore does not remove deletedAt

### ISSUE THREAD

**Issue by ben-sc** [dsanel/mongoose-delete#110]
I compared the result of static function vs instance function of restore,
they both successfully update `deleted` to false, but only instance function remove `deletedAt`

![image](https://user-images.githubusercontent.com/70249374/136249141-7771f341-cb71-4d5b-9ef3-933199806971.png)

**Comment by ben-sc** [comment]
A simple way to fix this is not to update with undefined, but to use unset instead. 

`
    schema.statics.restore =  function (conditions, callback) {
        if (typeof conditions === 'function') {
            callback = conditions;
            conditions = {};
        }

        var doc = {
            $unset:{
                deleted: true,
                deletedAt: true,
                deletedBy: true
            }
        }

        console.log("deleting?",doc)
        return updateDocumentsByQuery(this, conditions, doc, callback);
    };`

**Comment by dsanel** [comment]
Will be included in v1.0.0.
