### ISSUE TITLE
Bulk delete and restore with transactions

### ISSUE THREAD

**Issue by Guergeiro** [dsanel/mongoose-delete#117]
Currently there's no way of using a `ClientSession` to bulk delete/restore. I would propose the following API:

```js
Pet.delete({age:10}, idUser, {session: session}).exec(function (err, result) { ... });
```

Keep in mind this is just an example for `ClientSession`. Maybe using more parts of `QueryOptions` as the last argument could be interesting, just not a use case I can think of.

**Comment by dsanel** [comment]
@Guergeiro really interesting idea, if you can create PR I will gladly check and merge it. Thx
