### ISSUE TITLE
Perform additional changes on delete

### ISSUE THREAD

**Issue by SergioArrighi** [dsanel/mongoose-delete#120]
Hello all,

I am looking for a way to perform additional changes to my document when delete is invoked.
I checked a little bit the code and it doesn't seem to me like it it supported.
Also mongoose doesn't provide pre/post hooks for delete so I was wondering what is the best way to achieve this.

Thanks and best regards

**Comment by dsanel** [comment]
Currently, we don't have support for this. It can be interesting to have it. If you create PR I will be happy to check and add it to the repo.
