### ISSUE TITLE
Override Mongoose Delete Methods Same way you are overriding Find Methods

### ISSUE THREAD

**Issue by meilechwieder** [dsanel/mongoose-delete#121]
Why don't you override `findByIdAndDelete` so that it does not hard delete but instead only soft deletes it, the same way you are `find` only to find not deleted documents

**Comment by meilechwieder** [comment]
Same with `deleteOne`, `deleteMany`

**Comment by madilekci-avena** [comment]
Because you may want to use soft deletes in some places but hard delete in some other ?

**Comment by meilechwieder** [comment]
Yeah but I don’t want to mistakenly hard delete anything
