### ISSUE TITLE
Cannot save a deleted document

### ISSUE THREAD

**Issue by alejandro-martinez** [dsanel/mongoose-delete#122]
Hi there, I'm stuck with this issue: I cannot update a record via .save() if the record was already deleted

Record in db = {
    ...
   _id: new ObjectId("6272dc2837dc90a8e1c107ee"),
   deleted: true,
}

const connector = await this.schema.Connector.findOneWithDeleted({ _id: new ObjectId("6272dc2837dc90a8e1c107ee") });
const updatedConnector = await connector.save();

I'm getting:

error: DocumentNotFoundError: No document found for query "{ _id: new ObjectId("6272dc2837dc90a8e1c107ee") }" on model "Connector"

**Comment by dsanel** [comment]
This is expected behavior. The deleted document is "deleted". You can restore it, update and delete it again. Delete = soft-delete.
