### ISSUE TITLE
No deleted documents showing up

### ISSUE THREAD

**Issue by parichit13** [dsanel/mongoose-delete#13]
Hi,
I implemented the mongoose-delete plugin in my API and while creating new documents I was able to see the deleted tag.
![image](https://cloud.githubusercontent.com/assets/10647142/17058852/e3001ac6-503f-11e6-8c6a-ed77dd080c3b.png)
But after deleting the documents with 'findByIdAndRemove' no documents are showing up. I have applied the method override and deletedAt options but database contains no documents. The files have been permanently deleted.
```
UserSchema.plugin(mongoose_delete, {
	deletedAt: true,
	overrideMethods: true
});

```
I have even tried using 'findDeleted' and 'findWithDeleted'. Please help me out with this issue`

**Comment by dsanel** [comment]
Hi @parichit13,

`findByIdAndRemove` is not part of this plugin, it is standard Mongoose methods and it will definitely permanently remove the document from a collection. You can check it here: http://mongoosejs.com/docs/api.html#model_Model.findByIdAndRemove

In short, if you use `remove` method you actually use  standard Mongoose method and it will permanently remove documents from DB. Instead, you can use `delete` methods from `mongoose-plugin` and documents will not be deleted. You can find very simple example here: https://github.com/dsanel/mongoose-delete#simple-usage
