### ISSUE TITLE
Unsupported moongoose version 7.0.3

### ISSUE THREAD

**Issue by ayoubjemai** [dsanel/mongoose-delete#133]

**Comment by ayoubjemai** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: mongoose-delete@0.5.4
npm ERR! Found: mongoose@7.0.3
npm ERR! node_modules/mongoose
npm ERR!   mongoose@"^7.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"4.x || 5.x || 6.x" from mongoose-delete@0.5.4
npm ERR! node_modules/mongoose-delete
npm ERR!   mongoose-delete@"^0.5.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: mongoose@6.11.2
npm ERR! node_modules/mongoose
npm ERR!   peer mongoose@"4.x || 5.x || 6.x" from mongoose-delete@0.5.4
npm ERR!   node_modules/mongoose-delete
npm ERR!     mongoose-delete@"^0.5.4" from the root project

**Comment by dsanel** [comment]
Work in progress, the new version (`1.0.0`) will be relesed tomorrow.

**Comment by dsanel** [comment]
Done
