### ISSUE TITLE
Custom name for deleted field

### ISSUE THREAD

**Issue by jeremyjs** [dsanel/mongoose-delete#14]
I'd like to be able to set a custom name for the `deleted` field, for instance, to follow the convention of using a question for boolean fields, i.e. `isDeleted`.

Ideally, I could use a configuration option like so:

```
MySchema.plugin(mongoose_delete, { deletedFieldName: 'isDeleted' });
```

**Comment by dsanel** [comment]
Interesting proposal definitely!
I will try to find same time in next several days to implement this new option.

**Comment by dsanel** [comment]
Hi @jeremyjs 
after additional thinking related to this request and after testing I will refuse this `feature request`.

Currently, we have a lot of different features and options linked to word `deleted`. We have `deleted`, `deletedAt`, `deletedBy`, `countDeleted`, `findWithDeleted`... It will be a lot of work to implement all those names dynamically and it will add additional unnecessary complexity into the module.

Of course, you can always create a fork and add those simple changes for your specific needs.

**Comment by Angelo8828** [comment]
+1
