### ISSUE TITLE
Type Script - WithDeleted methods are not available

### ISSUE THREAD

**Issue by durveshparmar** [dsanel/mongoose-delete#142]
Hi, 

Whenever I try to use any "withDeleted" method to retrieve the records or update the records, it just doesn't find the function or method. 

`Property 'findDeleted' does not exist on type 'Model<Document, {}, {}, {}, any>'`

Please add the typescript support for this. I just love this package. I know there are others in the market but I find this one as the best. 

Please provide the support. Thanks in Advance.

Looking forward for the solution.

**Comment by durveshparmar** [comment]
Hi, 

I fixed this issue. 
I was doing as following before: 

`const model: SoftDeleteModel = model<Pet>('Pet', PetSchema);`

Fixed this issue by doing as per following: 
`const model = model<Pet, SoftDeleteModel<Pet>>('Pet', PetSchema);`

Thanks.

**Comment by suman379** [comment]
@durveshparmar , It worked.
