### ISSUE TITLE
Module should support Mongoose v7

### ISSUE THREAD

**Issue by a3957273** [dsanel/mongoose-delete#146]
Some casual testing suggests it does appear to be default, but I haven't used any complex features of the library.

**Comment by dest4** [comment]
I have issues with Mongoose v7, regarding callback support, which was dropped in that version https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support

For example, this line https://github.com/dsanel/mongoose-delete/blob/master/index.js#L248 throws the error `MongooseError: Model.prototype.save() no longer accepts a callback`

**Comment by dsanel** [comment]
@dest4 can you please provide a code example for this error?  All out tests pass on all supported versions of mongoose.
