### ISSUE TITLE
Support mongoose@8.0.0

### ISSUE THREAD

**Issue by krishnabrq** [dsanel/mongoose-delete#147]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@1.0.0
npm ERR! Found: mongoose@8.0.0
npm ERR! node_modules/mongoose
npm ERR!   mongoose@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"5.x || 6.x || 7.x" from mongoose-delete@1.0.1
npm ERR! node_modules/mongoose-delete
npm ERR!   mongoose-delete@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by sscots** [comment]
+1

**Comment by huyenvan12** [comment]
+1

**Comment by ernestognw** [comment]
+1

**Comment by arun-nd** [comment]
+1

**Comment by radosdaniel** [comment]
+1

**Comment by dsanel** [comment]
Fixed
