### ISSUE TITLE
Is there a deleteById?

### ISSUE THREAD

**Issue by harttle** [dsanel/mongoose-delete#16]
Plans for mongoose like delete APIs? I did not see it in the doc.

**Comment by dsanel** [comment]
Currently, I do not have time for it, but it can be interesting to have it. :)

Can you create pull request with proposed solution?

**Comment by niallobrien** [comment]
This would be a nice feature.

**Comment by Boltmerz** [comment]
There is a function findByIdAndRemove()

**Comment by dsanel** [comment]
This feature will be implemented in `v0.5.0`, currently in development.

@bhargav-sae, your code from #32 PR will be used in `v0.5.0` directly. You can check slightly changed code [here](https://github.com/dsanel/mongoose-delete/blob/ver-0-5-0/index.js#L211-L222). Thank you for your contribution!
