### ISSUE TITLE
No hooks on bulk delete

### ISSUE THREAD

**Issue by dirchev** [dsanel/mongoose-delete#17]
I spotted one thing, that can be improved. 

When we are making bulk delete, for example:

```js
Model.delete({_id: {$in: idsToDelete}}, function (err) {
  ...
})
```

`Model.delete` uses either `Model.update` or `Model.updateWithDeleted` method in order to update all the documents. ([the code](https://github.com/dsanel/mongoose-delete/blob/master/index.js#L201-L205)). This does not invoke any middlewares, validators etc. Here is what is written in the mongoose documentation:

> Although values are casted to their appropriate types when using update, the following are not applied:
> * defaults
> * setters
> * validators
> * middleware
> If you need those features, use the traditional approach of first retrieving the document.

[link](http://mongoosejs.com/docs/api.html#model_Model.update)

I think an option like this will be very useful. A simple example is deleting a bunch of users using a `pre-save` hook, which will change their emails, so that they do not conflict in the future when the same email is registered again.

I suggest an option in `Model.delete` will do the job, but let me hear you opinion first.

Cheers!

**Comment by dsanel** [comment]
I try to keep `mongoose-delete` clean and simple as possible. My main guidelines it to follow standard Mongoose features as much as I can and do not introduce new features that differ from the main framework.

From my perspective, this will add a nonstandard option to `delete` method. If we refer to Mongoose documentation [Model.remove](http://mongoosejs.com/docs/api.html#model_Model.remove), we can see that standard remove method is build to work as simple and as fast as possible.

> **Note:**
> This method sends a remove command directly to MongoDB, no Mongoose documents are involved. Because no Mongoose documents are involved, _no middleware (hooks) are executed_.

**Comment by dsanel** [comment]
I will close this issue, but if you like you can create simple PR with your proposal for a solution and we can test is and discuss it.
