### ISSUE TITLE
Population with deleted docs

### ISSUE THREAD

**Issue by aberezkin** [dsanel/mongoose-delete#21]
When you override `find` method you can't populate with deleted documents, but it would be useful sometimes.

I believe that the easiest workaround now is to implement `findWithoutDeleted` or something like that to not override `find` method.

**Comment by dsanel** [comment]
Hi @aberezkin 

we already have this feature using `findWithDeleted` method. This method will return all documents (DELETED and NOT DELETED). More information and code example you can find [here](https://github.com/dsanel/mongoose-delete#method-overridden).

Let me know if this is not what you need. ;)

**Comment by aberezkin** [comment]
No, this method is not what I need.

The key point is that when someone uses your plugin to override `find` method he always lose the ability to populate documents if referenced doc was deleted. But this can be useful in some cases. For example, if you want to log history of user's orders in your app, but some of the items in the order were marked as deleted (but you still need to show these in the history).

**Comment by svengau** [comment]
Hi, 
I've proposed you this PR to solve this issue:  
https://github.com/dsanel/mongoose-delete/issues/21

Thanks,
Sven

**Comment by johnyzv** [comment]
Hi,

This is my workaround until #21 gets merged
```
SomeSchema.pre("find", function() {
  const { withDeleted } = this.options;
  if (withDeleted) {
    delete this.getFilter().deleted;
  }
});
```
PS: I added this on every schema that uses this plugin

Cheers,
Johny
