### ISSUE TITLE
Custom typeKey

### ISSUE THREAD

**Issue by jeremejevs** [dsanel/mongoose-delete#22]
Please use schema's `typeKey` in `schema.add`, instead of assuming the default `type`.

**Comment by dsanel** [comment]
Is there any specific reason to use `Schema.Types.Boolean` or `Schema.Types.Date` as opposed to `Boolean` or `Date`?

If you check Mongoose validation code for those "standard" types, you will notice that they use _standard JavaScript data types_.

**Comment by jeremejevs** [comment]
I believe you have misunderstood me. I'm talking about [the `typeKey` option of `Schema`](http://mongoosejs.com/docs/guide.html#typeKey). When parsing a schema, Mongoose looks for the key `type` everywhere, and if it finds one, then it interprets the containing object as a type declaration. However, it isn't hardcoded, and it can be any key you want, defined by the `typeKey` option. I personally prefer `$type`, for multiple reasons (even Mongoose people want to prefix everything with `$` in the future, [source 1](https://github.com/Automattic/mongoose/issues/4688) / [source 2](https://github.com/Automattic/mongoose/issues/1760#issuecomment-159637322)), and [this line](https://github.com/dsanel/mongoose-delete/blob/24e782fd0797cfa546e762510b39c76a6bfca4a3/index.js#L80) has prevented me from using `mongoose-delete` in a project I was working on back in May.

**Comment by dsanel** [comment]
You are totally right, I misunderstood you. I hope that new commit will encourage you to use `mongoose-delete`. ;)

**Comment by jeremejevs** [comment]
Thanks!
