### ISSUE TITLE
Support types other than ObjectId for deletedBy

### ISSUE THREAD

**Issue by andreyrd** [dsanel/mongoose-delete#23]
I use string user ids because my user profiles come from an outside service not on MongoDB, and trying to set deletedBy to one of these strings causes:

```
MongooseError: Cast to ObjectId failed for value "xxxxxxxxxxxxxxxxx" at path "deletedBy"
```

**Comment by andreyrd** [comment]
I can create a PR with the necessary changes, I'm just wondering what the best way to do this would be.
Should deletedBy just be changed to a String completely?
Maybe add a deletedByType option where the user can specify the type?

**Comment by dsanel** [comment]
Thx for help @andreyrd #25
