### ISSUE TITLE
Add overridden findOneAndDelete()

### ISSUE THREAD

**Issue by andreyrd** [dsanel/mongoose-delete#26]
When I need the document returned from a delete, I could do the following with `remove()`:

```
const doc = await MySchema.remove({ _id: someId }).exec();
// Use doc
```

But with soft delete, the document is not returned, but instead a sort of status code:

```
const doc = await MySchema.delete({ _id: someId }).exec();
// doc = { n: 1, nModified: 1, ok: 1 }
```

**Comment by andreyrd** [comment]
Sorry, I was actually using `findOneAndRemove` previously. It would be nice to add `findOneAndDelete`.

**Comment by dsanel** [comment]
This is an interesting proposal, but it will be tricky to mix `findOneAndDelete` method with other [overridden methods](https://github.com/dsanel/mongoose-delete#method-overridden).

Maybe you can create PR, maybe proposal for this solution and we can work togeather on it.

**Comment by dsanel** [comment]
@andreyrd in `v0.5.0` we will have a method `deleteById`. I hope it will help you to easily use plugin. ;)

**Comment by HoseinGhanbari** [comment]
still getting `{ n: 1, nModified: 1, ok: 1 }` while using `delete` or `deleteById`

**Comment by farukborann** [comment]
how can i get deleted document in callback or something ? still work like that : { n: 1, nModified: 1, ok: 1 }
