### ISSUE TITLE
Is there any way I can populate deleted collection?

### ISSUE THREAD

**Issue by bhargav-sae** [dsanel/mongoose-delete#29]
I am using `overrideMethods: true`, because of that it is not populating that collection.

I am storing all activity logs, so in future I would like to go through all activities that affected any collections, so at that time I will need to populate any collections that got deleted by someone.

Is there any way to do that?

**Comment by crossRT** [comment]
same issue here.
Any suggestion for including deleted records for model population?

**Comment by crossRT** [comment]
@dsanel could you suggest us how should we do this?

**Comment by dsanel** [comment]
Hi @bhargav-sae and @crossRT,

if I understand your question correctly, you want an option to populate and update "deleted" document. You can do it with `findDeleted / findWithDeleted` and `updateDeleted 
 / updateWithDeleted`.

You can find more info and examples here: https://github.com/dsanel/mongoose-delete#method-overridden

**Comment by crossRT** [comment]
Hi @dsanel,
ya, but when we populate with mongoose, it doesn't retrieve the deleted record.
For example:

```javascript
Vehicle.findOne({ _id: vehicleId})
    .populate('vehicleTypeId')
    .then((vehicle) => {})
...
```
If the vehicleType is deleted, then it won't included in the vehicle.

**Comment by dsanel** [comment]
In short, Mongoose uses multiple queries to fulfill the request for populate. You can see the queries Mongoose is using by enabling debug output:
```
mongoose.set('debug', true);
```

This is definitely interesting to investigate, thanks for report :)

**Comment by crossRT** [comment]
Yeah. when populating the vehicleType, the mongoose is using `find()` method.
If we override `find()` method for the model, then it will not showing deleted records in listing and also the populate result.

**Comment by bhargav-sae** [comment]
@dsanel I am interested to investigate and submit a PR if possible.

**Comment by hellosandeep** [comment]
Thanks dsanel for giving option to get record findWithDeleted. but concern is if populating other collection in which record is deleted after populate getting null for that record.

**Comment by Tsourdox** [comment]
Any updates on this issue? Would be really nice to be able to populate fields where the referenced document has been soft deleted.

**Comment by Tsourdox** [comment]
Something like `populateWithDeleted` would do the trick in my case. Then I could just replace populate with this new function where it's needed to populate deleted documents. Is this hard to implement?

**Comment by dsanel** [comment]
I didn't investigate this option @Tsourdox, will check it. I am planning to spend some time on `populate` issue but honestly, I am thinking will this add additional complexity into soft delete plugin. We already have a lot of different options...

**Comment by sumixav** [comment]
Hi, wondering if there's any update on this?

**Comment by awalmubarak** [comment]
Hello, please is there any update on this?

**Comment by softmantk** [comment]
Any update on this ?

**Comment by iteratelance** [comment]
Hello All, I was also seeking this out and found https://www.npmjs.com/package/@yastech/mongoose-delete

```
.populate({ path: 'country', options: { withDeleted: true } })
```

**Comment by johnyzv** [comment]
This is my workaround
```
SomeSchema.pre("find", function() {
  const { withDeleted } = this.options;
  if (withDeleted) {
    delete this.getFilter().deleted;
  }
});
```
Usage:
```
SomeOtherModel.findOne({ ... }).populate({
  path: "...",
  options: { withDeleted: true },
});
```

PS: I added this on every schema that uses this plugin and works

**Comment by SergioArrighi** [comment]
Hello all,
I'm facing the same exact need.
I tried what @johnyzv proposed but as I'm using Typescript I get an error on this.options:
`The property 'options' doesn't exist in the type 'Query<any, any, {}, any>'.ts(2339)`

I also tried what @iteratelance suggested as I found it in the specs but it doesn't work for me right off the bat.

I have a fairly complex model I want to populate

`let as: A[] = await this.aModel.find({}).populate({
      path: 'bs',
      match: conditions,
      options: { withDeleted: true },
      model: B,
      transform: (doc: B) => new B(doc),
      populate: {
        path: 'cs',
        model: C,
        transform: (doc: C) => new Desk(C)
      }
    }).populate({
      path: 'ds',
      model: D,
      transform: (doc: D) => new D(doc)
    }).lean({ virtuals: true }).exec()`

I use match with precompiled conditions (it works for all other cases) and transform to instantiate object to have @Exclude class-transform annotation working on my schema.
All the types here A, B, C and D are the basic typescript type (not the model, nor the schema, neither the document).

I would really appreciate any suggestion.

Thanks and best regards

**Comment by IbnAdamnet** [comment]
> Hello all, I'm facing the same exact need. I tried what @johnyzv proposed but as I'm using Typescript I get an error on this.options: `The property 'options' doesn't exist in the type 'Query<any, any, {}, any>'.ts(2339)`
> 
> I also tried what @iteratelance suggested as I found it in the specs but it doesn't work for me right off the bat.
> 
> I have a fairly complex model I want to populate
> 
> `let as: A[] = await this.aModel.find({}).populate({ path: 'bs', match: conditions, options: { withDeleted: true }, model: B, transform: (doc: B) => new B(doc), populate: { path: 'cs', model: C, transform: (doc: C) => new C(doc) } }).populate({ path: 'ds', model: D, transform: (doc: D) => new D(doc) }).lean({ virtuals: true }).exec()`
> 
> I use match with precompiled conditions (it works for all other cases) and transform to instantiate object to have @exclude class-transform annotation working on my schema. All the types here A, B, C and D are the basic typescript type (not the model, nor the schema, neither the document).
> 
> I would really appreciate any suggestion.
> 
> Thanks and best regards


////////////////////////////////////////////////////////// FOR TYPESCRIPT /////////////////////
SomeSchema.pre("find", function() {
>   const { withDeleted } = this.["options"];
>   if (withDeleted) {
>     delete this.getFilter().deleted;
>   }
> });
