### ISSUE TITLE
Schema.Methods issue

### ISSUE THREAD

**Issue by enkodellc** [dsanel/mongoose-delete#3]
I ran into this issue and I would like to post it for others to see or maybe there is another possible fix.  The Schema methods were combined in an object which worked perfectly fine without the mongoose-delete. But after implementing the plugin and firing to delete / restore I would get an __undefined is not a function__.  To solve the issue I had to break out each Schema.method individually. I am not sure if anyone else out there used this syntax but I had it leftover for MEAN.IO.

My Schema has methods that were declared: 
```
/**
 * Methods
 */
UserSchema.methods = {
  hasRole: function(role) {
    var roles = this.roles;
    return roles.indexOf('admin') !== -1 || roles.indexOf(role) !== -1;
  },
  isAdmin: function() {
    return this.roles.indexOf('admin') !== -1;
  }
};
```

For it to work with  mongoose-delete I need to convert it to:
```
  UserSchema.methods.hasRole= function(role) {
    var roles = this.roles;
    return roles.indexOf('admin') !== -1 || roles.indexOf(role) !== -1;
  }

  UserSchema.methods.isAdmin = function() {
    return this.roles.indexOf('admin') !== -1;
  };
```

**Comment by dsanel** [comment]
Hi @enkodellc 
I believe that you actually override methods with your first version of the code. If you use `UserSchema.methods = {}` you actually create new methods object and override all existing methods.

**Comment by enkodellc** [comment]
Thanks for clarifying

**Comment by lucasvinals** [comment]
Hi @dsanel,
Can we use **.delete** method inside **statics** object of the schema?
I want to simplify some triggers when delete a document, so I created a static method. Inside that method, I want to use **.delete**.

Something like:

`deviceSchema.statics.deleteAndUpdate = (id) => {
  return deviceSchema.delete({ _id }).exec();
}`

**Comment by dsanel** [comment]
Hi @lucasvinals,

we have implementation for `method` and `static` implementation for this method. You can check it here: https://github.com/dsanel/mongoose-delete/blob/master/index.js#L157-L208

Example how to use it you can find in our tests: https://github.com/dsanel/mongoose-delete/blob/master/test/index.js#L733-L805

I didn't test it, but can you please try to use `this` in your code. I didn't test it but maybe it will work. :)

Example:
```
deviceSchema.statics.deleteAndUpdate = (id) => { return this.delete({ _id: id }).exec(); }
```
