### ISSUE TITLE
{ indexFields: true } does not work

### ISSUE THREAD

**Issue by HackedBeat** [dsanel/mongoose-delete#33]
The docs says:

``` js
// Index all field related to plugin (deleted, deletedAt, deletedBy)
PetSchema.plugin(mongoose_delete, { indexFields: 'all' });
// or 
PetSchema.plugin(mongoose_delete, { indexFields: true });
```
But it doesn't work. Only the ```deleted``` field will be added to the database. At the moment, these fields can only be added manually: 
``` js
PetSchema.plugin(mongoose_delete, { indexFields: true, deletedAt: true, deletedBy: true });
 ```

**Comment by adamgall** [comment]
I think you have misunderstood the purpose of `indexFields: true`.

that property will add an _index_ to all `mongoose-delete` fields which have been enabled.

So yes, it makes sense that you must enable `deletedAt` and `deletedBy` if you want `indexFields: all` to create an index for them.
