### ISSUE TITLE
Bulk soft-delete / restore

### ISSUE THREAD

**Issue by enkodellc** [dsanel/mongoose-delete#4]
I want to do soft-delete and then possibly restore a group of related items, requiring a find query. My soft-deletes do have the deletedBy option. Basically I would like to do a find and soft-delete / find and restore in one call instead of doing a find and then going walking though each object to soft-delete / restore So I thought I could chain it like so but it fails:

`
Modal.find({'name': name._id}).delete(req.user._id, function(err) {});
`

It works if walk though them but it seems like this would be much slower:
`
       Modal.find({'name': name._id})
          .select('_id')
          .exec(function(err, modals) {
            for(var i = 0; i < modals.length; i++) {
              modal[i].delete(req.user._id, function(err) {});
            }
        });
`

**Comment by dsanel** [comment]
Hi @enkodellc, thx for proposal!

In new version we have bulk delete and restore methods: https://www.npmjs.com/package/mongoose-delete#bulk-delete-and-restore

**Comment by enkodellc** [comment]
Awesome, love using this.
