### ISSUE TITLE
[Discuss] Should we create separate delete and deleteByUser to avoid confusion

### ISSUE THREAD

**Issue by taina0407** [dsanel/mongoose-delete#41]
Hello,

I'm currently using mongoose-delete in production, and while a team working together, we have to review code a lot, but the way to use mongoose-delete like
```javascript
let subject = await SubjectModel.findOne(condition);
// some logics
await subject.delete(idUser);
```
it look a bit confuse for me, it look like it trying to delete subject by `idUser`
I'm wondering that could we change the method name to be more specific like

```javascript
await subject.delete(); // Without deleteBy option
```
and
```javascript
await subject.deleteByUser(idUser); // With deleteBy option
```

I think this way will make the code is easier for reading and understanding.

**Comment by dsanel** [comment]
Hi @taina0407, this can be an interesting feature. If you create PR I will be happy to check and merge it.
