### ISSUE TITLE
[BUG] overrideMethods, callback not working!

### ISSUE THREAD

**Issue by fogarasyroland** [dsanel/mongoose-delete#42]
Works:
models.User.find({_id: req.userID}, { password: 0 }).exec((err, user) => {})

Not work (I get deleted user too):
models.User.find({_id: req.userID}, { password: 0 }, (err, user) => {})

**Comment by V1os** [comment]
https://github.com/dsanel/mongoose-delete/blob/master/index.js#L134 
this line have a interest feature.

console.log('sd -->', method, arguments); 
// sd -->  "find" [Arguments] {'0' {_id: req.userID}, '1': { password: 0 }, '2': [Function: post] }

Where did the third argument come from?

**Comment by V1os** [comment]
function post(error, res) {
              if (postCalled++ > 0) {
                return;
              }

              if (error != null) {
                return callback(error);
              }

              hooks.execPost(key, model, [res], function(error) {
                if (error != null) {
                  return callback(error);
                }
                callback(null, res);
              });
            }

**Comment by V1os** [comment]
https://github.com/Automattic/mongoose/blob/master/lib/helpers/model/applyStaticHooks.js#L34

**Comment by V1os** [comment]
Maybe you need a pre, post save middleware? http://mongoosejs.com/docs/middleware.html

**Comment by ajmas** [comment]
@V1os is this still an issue and does using promises work around the issue?

**Comment by V1os** [comment]
yes, question is settled. thanks
