### ISSUE TITLE
Add collection.countDocuments or collection.estimatedDocumentCount due to deprecation

### ISSUE THREAD

**Issue by gforge** [dsanel/mongoose-delete#45]
In MongoDb 4 they seem to have deptrecated the count into two new:

1. [countDocuments](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#countDocuments)
2. [estimatedDocumentCount](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#estimatedDocumentCount)

The user will get:
>node:1772) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. >Use collection.countDocuments or collection.estimatedDocumentCount instead

Since a non-suspecting user may change to this new method without thinking about the delete-plugin, this could turn out to be a problem for folks out ther...

**Comment by gforge** [comment]
I added some test cases and a quick fix: https://github.com/gforge/mongoose-delete/tree/MongoDB_4

Unfortunately the `estimatedDocumentCount` doesn't work as expected. The function uses metadata and it is unclear to me if it actually runs some form of query, if it updates at the metadata at certain time points, or if it simply has a collection count stored in the metadata. The latter could be problematic for this package to handle, most likely it would require a readme warning.

**Comment by dsanel** [comment]
Fixed in `v0.5.0`
