### ISSUE TITLE
TypeError: assignment.delete is not a function

### ISSUE THREAD

**Issue by rafalskyi** [dsanel/mongoose-delete#48]
example of error
TypeError: assignment.delete is not a function
```
export const destroy = ({ params }, res, next) =>
  Assignment.findById(params.id)
    .then(notFound(res))
    .then((assignment) => {
      return assignment.delete()
    })
    .then(success(res, 204))
    .catch(next)
```

method doesnt exists in fetched objects

**Comment by lsmar** [comment]
I find the reason for me here. 
The problem was that I have custom methods in my model and i was setting the plugin before the custom methods. When i set the plugin after the custom methods it works.

**Comment by rafalskyi** [comment]
in my case the issue was in  wrong schema methods initialisation
Schema.methods = {
   some_method:  function() { return 'a'}
}

and it removed all plugins methods as well

correct version:

Schema.methods.some_method = function() { return 'a'}


in this way it will not erase methods added by other plugin
