### ISSUE TITLE
The return value of schema.statics.delete() is right ?

### ISSUE THREAD

**Issue by maranran** [dsanel/mongoose-delete#49]
I wonder why the value of schema.statics.delete() is `this.update(conditions, doc, { multi: true }, callback);` not like `this.update(conditions, doc, { multi: true }, callback).where('deleted').ne(true)`, the difference is their return value，actually is the  nModified's value

**Comment by HoseinGhanbari** [comment]
is the return value of schema.statics.delete() is right ? **ABSOLUTELY NO**

please fix this issue......
