### ISSUE TITLE
do not use $ne operator

### ISSUE THREAD

**Issue by gabzim** [dsanel/mongoose-delete#50]
In large collections, the `$ne` operator is very inefficient and can make queries slow. (https://docs.mongodb.com/manual/reference/operator/query/ne/ last paragraph). 

I recently had to investigate performance troubles we're having in one of our largest collections and it's due to the use of this plugin. What I'd suggest is maybe always keeping `deleted` as `false` and then doing `{$eq: false}` to retrieve active documents.

**Comment by tcstory** [comment]
assume I had the following documents, the documents were producted before I use mongoose-delete plugin,

```
{_id: 'xx', name:1},
{_id: 'xx', name:2},
{_id: 'xx', name:3},
```
and now I start to use this plugin, because it use `$ne` operator, so  it will treat these documents as **undeleted**, this is what I need. but if it use `$eq` operator, I have to add `deleted: false` to every documents.

**Comment by gabzim** [comment]
True, but if your collection has 1,000,000 docs instead of 3 a query that does not filter them out by an index will timeout. And this can get unpredictable as it will happen in some collections and it won't in others.

**Comment by bdelville** [comment]
It is in pull request

**Comment by dsanel** [comment]
This type of changes can affect existing users and I really try to keep back compatibility with older versions. This is the main reason why I introduce new option `use$neOperator` so you can override default behavior (default is `{use$neOperator: true}`).

This new option will cover both scenarios. 

https://github.com/dsanel/mongoose-delete/blob/master/test/index.js#L1598-L1654

Hope this will help @gabzim? ;)

**Comment by simplenotezy** [comment]
FYI I just tried doing a comparison, and inside a collection of +1mn documents, and I didn't see any noticeable difference.

Am I missing something?

Using `deleted: {$ne: true}`
-
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/3786627/168984034-3dbf297c-af56-4818-bef2-3d98963b32f5.png">


Using `deleted: false`
-
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/3786627/168983884-9637f6aa-0a1a-4a4a-bfd3-ee5ad257aa89.png">
