### ISSUE TITLE
Use mongoose-delete on fields, not schema

### ISSUE THREAD

**Issue by thecamarada** [dsanel/mongoose-delete#51]
I didn't find anything related. It's possible to use mongoose-delete (soft delete) on fields instead only on Schema?

For example:

```
posts: {
	_id: '1qa2ws,
	title: 'New Post',
	comments: [{
		userId: '123',
		comment: 'Nice!',
	},
	{
		userId: '321',
		comment: 'Bad comment!',
		deleted: true,
		deletedBy: '123',
		deletedAt: 1990-10-10T20:00:00
	}],
}
```

If it doesn't exist, it would be a great feature.

**Comment by dsanel** [comment]
This will require a significant amount of work. I don't have a plan to implement this in near future. All good PR is welcome.
