### ISSUE TITLE
Mongoose type error

### ISSUE THREAD

**Issue by TudorIoanMarin** [dsanel/mongoose-delete#57]
Hi,

I'm trying to run the library on a typescript project. I have mongoose@5.2.5 and @types/mongoose@5.2.2. I am using the plugin as per the instructions. I also have:
interface ItemStructure extends Document {
...
}

const ItemSchema = new Schema({ ... })

ItemSchema.plugin(mongoose_delete, { overrideMethods: 'all' });

export const Item: Model<ItemStructure> = model(
    'item',
    ItemSchema
);

For some reason it appears that there is no delete function on type Model<Document> event after I extend the Item interface with said method. I am trying to replace some findByIdAndRemove query's with soft delete. 

Error: 
 Property 'delete' does not exist on type 'Model<ItemStructure, {}>'

Additional info:
"os":"linux","arch":"x64"

Any help would be appreciated.

**Comment by htwibowo** [comment]
+1, ES Lint throwing errors when calling extended methods (`findDeleted`,  `findWithDeleted`, etc.)

**Comment by TheDeathStreaker** [comment]
To fix that typing issue install package @types/mongoose-delete and than instead of using `Model<ItemStructure, {}>` use `SoftDeleteModel<ItemStructure, {}>`

**Comment by ajmas** [comment]
@adrianjarc would it be worth adding something on this into the Read Me?

**Comment by adrianjarc** [comment]
@ajmas It would. But as I look at the state of this repository, I highly doubt it will get merged, even if I or anyone else makes this PR

**Comment by dsanel** [comment]
@adrianjarc @ajmas If you add some README instructions and create PR, I will be happy to check and merge it.

**Comment by ajmas** [comment]
I have created a PR with an example in Typescript. @adrianjarc if you have any suggestions on improving the example, please let me know.
