### ISSUE TITLE
instance.delete() should desactivate/skip model validation

### ISSUE THREAD

**Issue by marchah** [dsanel/mongoose-delete#6]
Hi,

When you want to `delete` a document and for example a required field is not present you get a validation error but it doesn't make sense to validate the data if you want to delete it.

http://stackoverflow.com/questions/27199208/skip-or-disable-validation-for-mongoose-model-save-call

Thanks

**Comment by dsanel** [comment]
hi @marchah,

thx for your feedback and proposal. I create an additional solution for this so the user can decide to use it or now. I hope that this solution will be good for your specific case.

Best regards

**Comment by marchah** [comment]
@dsanel perfect thanks
