### ISSUE TITLE
Question: How to print result into an object deleteStatus: {}

### ISSUE THREAD

**Issue by ruslanguns** [dsanel/mongoose-delete#61]
I would like to create an Object with all the Delete info, instead to be in the root of the model.

Something like this: 

```ts
export const UserSchema = new Schema({
    firstName: String,
    lastName: String,
    phone: String,
    deleteStatus: {  // RIGHT HERE
           delete: Boolean,
           deletedBy: ObjectId,
           deletedAt: Date,
    },
});
```

By the way, any news about the @types for TypeScript?

Thank you in advance!

**Comment by dsanel** [comment]
https://www.npmjs.com/package/@types/mongoose-delete
