### ISSUE TITLE
easy integration?

### ISSUE THREAD

**Issue by waptik** [dsanel/mongoose-delete#64]
Isn't there a way to integrate this plugin easily across all models/schemas like
```js
const mongoose = require('mongoose');
const mongoose_delete = require('mongoose-delete');
mongoose_delete(mongoose);
```
 than to hook it through this for every schema
```js
const mongoose = require('mongoose');
const mongoose_delete = require('mongoose-delete');

const schema = new mongoose.Schema({ ... });
schema.plugin(mongoose_delete );
```

[mongoose-association](https://github.com/vickenstein/mongoose-association) does it.

**Comment by sanudatta11** [comment]
+1 Need this feature!

**Comment by cardimajs** [comment]
+1

**Comment by waptik** [comment]
> There is the option to include a plugin on all models by default on mongoose.
> 
> ```
> var mongoose = require('mongoose');
> var mongooseDelete = require('mongoose-delete');
> mongoose.plugin(mongooseDelete);
> ```

Sorry for the late reply.
Thanks. This is what i was looking for.
