### ISSUE TITLE
Aggregate queries

### ISSUE THREAD

**Issue by jordan-econify** [dsanel/mongoose-delete#65]
The Aggregate queries don't support the soft delete
I am forced to supply this key myself
```
aggregate([
    {
      $match: { deleted: false },
    },
    {
      $sort: { versionId: -1 },
    },
    {
      $group: {
        _id: '$route',
        id: { $first: '$_id' },
...
```
I wanted to check if there was a reason why this isn't supported?  I would consider writing a PR if we can discuss any potential issues or reasons why it wasn't done. Thanks!

**Comment by RsknCankov** [comment]
@jordan-econify check #31 .
