### ISSUE TITLE
collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead 

### ISSUE THREAD

**Issue by slash-senghak** [dsanel/mongoose-delete#78]
when I use the delete function of mongoose delete. It shows me this warning message.

**Comment by HoseinGhanbari** [comment]
as of 15 may 2020 still exists:

```
(node:13732) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
```

**Comment by HoseinGhanbari** [comment]
[**TEMPORARY SOLUTION**] you can get rid of this DeprecationWarning by turning off `update` and `updateMany` when applying plugin.

```
overrideMethods: [
    "count",
    "countDocuments",
    "find",
    "findOne",
    "findOneAndUpdate",
    // "update",
    // "updateMany",
  ],
```

**Comment by nishant-lambdaschool** [comment]
Please fix this issue. My manager is going crazy.

**Comment by dsanel** [comment]
[v0.5.3](https://github.com/dsanel/mongoose-delete/blob/master/CHANGELOG.md#v053)
