### ISSUE TITLE
Isn't a deletedAt field enough? instead of two deleted and deletedAt fields

### ISSUE THREAD

**Issue by meness** [dsanel/mongoose-delete#82]
I think using two fields (`deleted` and `deletedAt`) is unnecessary while `deletedAt === null || deletedAt === undefined` does the same.

A better solution is to have a virtual field called `deleted` based on the above-mentioned condition but only save/update a single field > `deletedAt`.

**Comment by meness** [comment]
To prevent breaking changes, you can define an option to disable `deleted` field by default.

**Comment by sayhicoelho** [comment]
It is nice to keep it in the payload because some client languages are strongly typed and returning null will throw an exception. But I agree with the option to remove 'deleted' field because some languages will not be affected.

**Comment by dsanel** [comment]
Field `deletedAt` is optional so we need to have two fields... Potentially, it can be rewritten to use only one field but it will require a lot of work and probably we would lose back compatibility
