### ISSUE TITLE
restore issue

### ISSUE THREAD

**Issue by Zarinia** [dsanel/mongoose-delete#83]
Hi, when use override method such as this:
```
overrideMethods: [
	'count',
	'countDocuments',
	'find',
	'findOne',
	'findOneAndUpdate',
	//'update',
	'updateMany',
	'aggregate'
],
```
and not include update, my restore not working.
please help me to fix this. thanks

**Comment by lord007tn** [comment]
`schema.statics.restore =  function (conditions, callback) {
        if (typeof conditions === 'function') {
            callback = conditions;
            conditions = {};
        }

        var doc = {
            deleted: false,
            deletedAt: undefined,
            deletedBy: undefined
        };

        if (this.updateWithDeleted) {
            return this.updateWithDeleted(conditions, doc, { multi: true }, callback);
        } else {
            return this[mainUpdateMethod](conditions, doc, { multi: true }, callback);
        }
    };`

this part from the package it self. restore is just an update method to database to change deleted filed from true to false again.  i don't see a problem there could you re create the problem in a sandbox
