### ISSUE TITLE
Error when use overrideMethods: true

### ISSUE THREAD

**Issue by xblue55** [dsanel/mongoose-delete#85]
when i set config is `overrideMethods:true`. I got error when use method find findOne ...
**My code:** 
`
const ProductOriginModel = mongoose.model('ProductOriginModel', ProductOriginSchema);
ProductOriginModel.find()
` 
**Error Message**
`Model.find()` cannot run without a model as `this`. Make sure you are not calling `new Model.find()`

**Comment by gtamas** [comment]
Same here if I try to register the plugin for all models (globally)

mongoose.plugin(...)

**Comment by xblue55** [comment]
Im fixed. Thanks for support

**Comment by szy0syz** [comment]
Same here.
How to fixed ?

**Comment by liuxyCN** [comment]
> `Model.find()` cannot run without a model as `this`. Make sure you are not calling `new Model.find()`
could u share how to fix it? thanks

**Comment by madilekci** [comment]
Same here, How did you fix that ?

**Comment by phytter** [comment]
same here, someone can help us?
