### ISSUE TITLE
deleteOne and deleteMany?

### ISSUE THREAD

**Issue by ajmas** [dsanel/mongoose-delete#87]
Would it be worth including `deleteOne` and `deleteMany` as functions, to follow the same naming conventions that mongoose is using these days?

**Comment by dsanel** [comment]
I was thinking about this and I am not sure what to do for sure... 

Functions `deleteOne` and `deleteMany` are functions from Mongoose and if we override them how we will really delete documents? 

The main idea behind the `mongoose-delete` plugin is to ADD an option to do **soft deletion** of documents. In many projects, I must do real delete and soft delete too. This is why we have completely different functions for soft delete (`delete`, `restore`).

Maybe we can add an option so the user can decide to completely override the main `deleteOne` and `deleteMany` functions?

@MalekBouba if you create PR I will gladly check it and include it in the plugin.
