### ISSUE TITLE
instance.delete() doesn't call hooks

### ISSUE THREAD

**Issue by marchah** [dsanel/mongoose-delete#9]
Hi,

Is there any ways to call the hooks `pre.remove` and `post.remove` when we use `delete()` ?

**Comment by dsanel** [comment]
Hi @marchah,

`delete() ` method actually use `save()` method, and I don't see any obstacle to using `schema.pre('save')` or `schema.post('save')`.

I didn't test this and if you find problems using this approach we can try to figure out another solution.
